FROM ubuntu:18.04

COPY ./poc/ /opt/poc/

RUN sed -i s@/archive.ubuntu.com/@/mirrors.tuna.tsinghua.edu.cn/@g /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update --fix-missing && apt-get install -y\
  curl \
  python3 \
  python3-pip \
  firefox
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple requests selenium lxml
CMD bash /opt/poc/poc.sh