FROM ubuntu:18.04

COPY config.sh /opt/data/config.sh
COPY filldata.py /opt/data/filldata.py
RUN sed -i s@/archive.ubuntu.com/@/mirrors.tuna.tsinghua.edu.cn/@g /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update && apt-get install -y \
  curl \
  python3 \
  python3-pip 
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple requests lxml
CMD bash /opt/data/config.sh