version: "3"
services:
  web:
     build:
       context: .
       dockerfile: Dockerfile
     #image: bludit:3.9.2-ssh
     container_name: bludit-3.9.2-web-app
     ports:
       - "8000:80"
       - "10003:22"
     restart: always
     stdin_open: true
     tty: true   
  config:
     build:
       context: .
       dockerfile: Dockerfile_config
     environment: 
       - PYTHONIOENCODING=utf-8
     container_name: bludit-3.9.2-config-app
     depends_on:
       - web
       
  poc:
     build:
       context: .
       dockerfile: Dockerfile_poc
     container_name: bludit-3.9.2-poc-app
     depends_on:
       - web
       - config
      
